"""create verification applications

Revision ID: 007326cfad11
Revises: c51b427b6bfc
Create Date: 2026-09-13 11:10:27.059279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '007326cfad11'
down_revision: Union[str, Sequence[str], None] = 'c51b427b6bfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification_applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('applicant_user_id', sa.UUID(), nullable=False),
    sa.Column('verifier_user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=40), server_default='PENDING', nullable=False),
    sa.Column('application_type', sa.String(length=50), nullable=False),
    sa.Column('submitted_data', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['applicant_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verifier_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_verification_applications_applicant', 'verification_applications', ['applicant_user_id', 'status'], unique=False)
    op.create_index('ix_verification_applications_type_status', 'verification_applications', ['application_type', 'status'], unique=False)
    op.create_index('ix_verification_applications_verifier', 'verification_applications', ['verifier_user_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_verification_applications_verifier', table_name='verification_applications')
    op.drop_index('ix_verification_applications_type_status', table_name='verification_applications')
    op.drop_index('ix_verification_applications_applicant', table_name='verification_applications')
    op.drop_table('verification_applications')
    # ### end Alembic commands ###
