"""create candidate skills

Revision ID: 0d29f3b286b5
Revises: f34be9c3c06e
Create Date: 2026-09-13 23:10:48.424758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d29f3b286b5'
down_revision: Union[str, Sequence[str], None] = 'f34be9c3c06e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_profile_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('proficiency_level', sa.String(length=30), server_default='BEGINNER', nullable=False),
    sa.Column('years_of_experience', sa.Float(), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=30), server_default='SELF_DECLARED', nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('verified_by_user_id', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['verified_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_profile_id', 'skill_id', name='uq_candidate_skill_profile_skill')
    )
    op.create_index('ix_candidate_skills_candidate_profile', 'candidate_skills', ['candidate_profile_id'], unique=False)
    op.create_index('ix_candidate_skills_proficiency', 'candidate_skills', ['proficiency_level'], unique=False)
    op.create_index('ix_candidate_skills_skill', 'candidate_skills', ['skill_id'], unique=False)
    op.create_index('ix_candidate_skills_status', 'candidate_skills', ['status'], unique=False)
    op.create_index('ix_candidate_skills_verified', 'candidate_skills', ['status', 'verified_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_candidate_skills_verified', table_name='candidate_skills')
    op.drop_index('ix_candidate_skills_status', table_name='candidate_skills')
    op.drop_index('ix_candidate_skills_skill', table_name='candidate_skills')
    op.drop_index('ix_candidate_skills_proficiency', table_name='candidate_skills')
    op.drop_index('ix_candidate_skills_candidate_profile', table_name='candidate_skills')
    op.drop_table('candidate_skills')
    # ### end Alembic commands ###
