"""create candidate credentials

Revision ID: 0db7ce7deb61
Revises: 0d29f3b286b5
Create Date: 2026-09-13 23:33:33.315472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0db7ce7deb61'
down_revision: Union[str, Sequence[str], None] = '0d29f3b286b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_profile_id', sa.UUID(), nullable=False),
    sa.Column('issuing_organization_id', sa.UUID(), nullable=True),
    sa.Column('credential_type', sa.String(length=40), server_default='CERTIFICATE', nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('credential_number', sa.String(length=255), nullable=True),
    sa.Column('issuing_organization_name', sa.String(length=255), nullable=False),
    sa.Column('issue_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('document_path', sa.String(length=500), nullable=False),
    sa.Column('document_hash', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='UPLOADED', nullable=False),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('verified_by_user_id', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('blockchain_transaction_hash', sa.String(length=255), nullable=True),
    sa.Column('blockchain_network', sa.String(length=100), nullable=True),
    sa.Column('is_public', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['issuing_organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verified_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_candidate_credentials_candidate', 'candidate_credentials', ['candidate_profile_id'], unique=False)
    op.create_index('ix_candidate_credentials_hash', 'candidate_credentials', ['document_hash'], unique=False)
    op.create_index('ix_candidate_credentials_issuer', 'candidate_credentials', ['issuing_organization_id'], unique=False)
    op.create_index('ix_candidate_credentials_number', 'candidate_credentials', ['credential_number'], unique=False)
    op.create_index('ix_candidate_credentials_status', 'candidate_credentials', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_candidate_credentials_status', table_name='candidate_credentials')
    op.drop_index('ix_candidate_credentials_number', table_name='candidate_credentials')
    op.drop_index('ix_candidate_credentials_issuer', table_name='candidate_credentials')
    op.drop_index('ix_candidate_credentials_hash', table_name='candidate_credentials')
    op.drop_index('ix_candidate_credentials_candidate', table_name='candidate_credentials')
    op.drop_table('candidate_credentials')
    # ### end Alembic commands ###
