"""create organization members

Revision ID: 1ba1f1affe0b
Revises: f65b0b065d81
Create Date: 2026-09-13 11:53:10.865181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ba1f1affe0b'
down_revision: Union[str, Sequence[str], None] = 'f65b0b065d81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_code', sa.String(length=50), nullable=False),
    sa.Column('invited_by_user_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'user_id', 'role_code', name='uq_organization_member_role')
    )
    op.create_index('ix_organization_members_org_active', 'organization_members', ['organization_id', 'is_active'], unique=False)
    op.create_index('ix_organization_members_role_active', 'organization_members', ['role_code', 'is_active'], unique=False)
    op.create_index('ix_organization_members_user_active', 'organization_members', ['user_id', 'is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_organization_members_user_active', table_name='organization_members')
    op.drop_index('ix_organization_members_role_active', table_name='organization_members')
    op.drop_index('ix_organization_members_org_active', table_name='organization_members')
    op.drop_table('organization_members')
    # ### end Alembic commands ###
