"""create jobs

Revision ID: 1c3102872177
Revises: 1ba1f1affe0b
Create Date: 2026-09-13 12:09:12.448604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c3102872177'
down_revision: Union[str, Sequence[str], None] = '1ba1f1affe0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('posted_by_user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('responsibilities', sa.Text(), nullable=True),
    sa.Column('qualifications', sa.Text(), nullable=True),
    sa.Column('employment_type', sa.String(length=50), nullable=False),
    sa.Column('workplace_type', sa.String(length=30), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=150), nullable=True),
    sa.Column('state', sa.String(length=150), nullable=True),
    sa.Column('country', sa.String(length=100), server_default='India', nullable=False),
    sa.Column('min_experience_years', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_experience_years', sa.Integer(), nullable=True),
    sa.Column('min_salary', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('max_salary', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('salary_currency', sa.String(length=10), server_default='INR', nullable=False),
    sa.Column('vacancies', sa.Integer(), server_default='1', nullable=False),
    sa.Column('application_deadline', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='DRAFT', nullable=False),
    sa.Column('is_featured', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['posted_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_employment_workplace', 'jobs', ['employment_type', 'workplace_type'], unique=False)
    op.create_index('ix_jobs_location', 'jobs', ['state', 'city'], unique=False)
    op.create_index('ix_jobs_organization_status', 'jobs', ['organization_id', 'status'], unique=False)
    op.create_index('ix_jobs_posted_by', 'jobs', ['posted_by_user_id'], unique=False)
    op.create_index('ix_jobs_status_deadline', 'jobs', ['status', 'application_deadline'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_jobs_status_deadline', table_name='jobs')
    op.drop_index('ix_jobs_posted_by', table_name='jobs')
    op.drop_index('ix_jobs_organization_status', table_name='jobs')
    op.drop_index('ix_jobs_location', table_name='jobs')
    op.drop_index('ix_jobs_employment_workplace', table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
