"""add government data access authorization

Revision ID: 25ed7da35044
Revises: ce818a96ec0a
Create Date: 2026-09-14 11:29:07.122222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25ed7da35044'
down_revision: Union[str, Sequence[str], None] = 'ce818a96ec0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('government_data_access_authorizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('government_unit_id', sa.UUID(), nullable=False),
    sa.Column('access_level', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('scope', sa.String(length=1000), nullable=True),
    sa.Column('granted_by_user_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['government_unit_id'], ['government_units.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['granted_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_gov_data_access_status', 'government_data_access_authorizations', ['status'], unique=False)
    op.create_index('ix_gov_data_access_unit', 'government_data_access_authorizations', ['government_unit_id'], unique=False)
    op.create_index('ix_gov_data_access_unit_status', 'government_data_access_authorizations', ['government_unit_id', 'status'], unique=False)
    op.create_index('ix_gov_data_access_user', 'government_data_access_authorizations', ['user_id'], unique=False)
    op.create_index('ix_gov_data_access_user_status', 'government_data_access_authorizations', ['user_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_gov_data_access_user_status', table_name='government_data_access_authorizations')
    op.drop_index('ix_gov_data_access_user', table_name='government_data_access_authorizations')
    op.drop_index('ix_gov_data_access_unit_status', table_name='government_data_access_authorizations')
    op.drop_index('ix_gov_data_access_unit', table_name='government_data_access_authorizations')
    op.drop_index('ix_gov_data_access_status', table_name='government_data_access_authorizations')
    op.drop_table('government_data_access_authorizations')
    # ### end Alembic commands ###
