"""add assessment attempt invitation answer tables

Revision ID: 2e3bbd6c14a2
Revises: e3a5ab937fcb
Create Date: 2026-09-14 21:18:34.787887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e3bbd6c14a2'
down_revision: Union[str, Sequence[str], None] = 'e3a5ab937fcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_invitations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('job_application_id', sa.UUID(), nullable=False),
    sa.Column('candidate_profile_id', sa.UUID(), nullable=False),
    sa.Column('invited_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('invited_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['job_application_id'], ['job_applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id', 'job_application_id', name='uq_assessment_invitation_assessment_application')
    )
    op.create_index('ix_assessment_invitations_application_status', 'assessment_invitations', ['job_application_id', 'status'], unique=False)
    op.create_index('ix_assessment_invitations_assessment_status', 'assessment_invitations', ['assessment_id', 'status'], unique=False)
    op.create_index('ix_assessment_invitations_candidate_status', 'assessment_invitations', ['candidate_profile_id', 'status'], unique=False)
    op.create_index('ix_assessment_invitations_expires_at', 'assessment_invitations', ['expires_at'], unique=False)
    op.create_table('assessment_attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invitation_id', sa.Uuid(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('candidate_profile_id', sa.UUID(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('answered_questions', sa.Integer(), nullable=False),
    sa.Column('correct_answers', sa.Integer(), nullable=False),
    sa.Column('wrong_answers', sa.Integer(), nullable=False),
    sa.Column('unanswered_questions', sa.Integer(), nullable=False),
    sa.Column('total_marks', sa.Float(), nullable=False),
    sa.Column('obtained_marks', sa.Float(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invitation_id'], ['assessment_invitations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invitation_id', 'attempt_number', name='uq_assessment_attempt_invitation_number')
    )
    op.create_index('ix_assessment_attempts_assessment_status', 'assessment_attempts', ['assessment_id', 'status'], unique=False)
    op.create_index('ix_assessment_attempts_candidate_status', 'assessment_attempts', ['candidate_profile_id', 'status'], unique=False)
    op.create_index('ix_assessment_attempts_invitation_status', 'assessment_attempts', ['invitation_id', 'status'], unique=False)
    op.create_index('ix_assessment_attempts_submitted_at', 'assessment_attempts', ['submitted_at'], unique=False)
    op.create_table('assessment_answers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('attempt_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('is_answered', sa.Boolean(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('marks_awarded', sa.Float(), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['assessment_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['assessment_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'question_id', name='uq_assessment_answer_attempt_question')
    )
    op.create_index('ix_assessment_answers_attempt', 'assessment_answers', ['attempt_id'], unique=False)
    op.create_index('ix_assessment_answers_attempt_correct', 'assessment_answers', ['attempt_id', 'is_correct'], unique=False)
    op.create_index('ix_assessment_answers_question', 'assessment_answers', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_assessment_answers_question', table_name='assessment_answers')
    op.drop_index('ix_assessment_answers_attempt_correct', table_name='assessment_answers')
    op.drop_index('ix_assessment_answers_attempt', table_name='assessment_answers')
    op.drop_table('assessment_answers')
    op.drop_index('ix_assessment_attempts_submitted_at', table_name='assessment_attempts')
    op.drop_index('ix_assessment_attempts_invitation_status', table_name='assessment_attempts')
    op.drop_index('ix_assessment_attempts_candidate_status', table_name='assessment_attempts')
    op.drop_index('ix_assessment_attempts_assessment_status', table_name='assessment_attempts')
    op.drop_table('assessment_attempts')
    op.drop_index('ix_assessment_invitations_expires_at', table_name='assessment_invitations')
    op.drop_index('ix_assessment_invitations_candidate_status', table_name='assessment_invitations')
    op.drop_index('ix_assessment_invitations_assessment_status', table_name='assessment_invitations')
    op.drop_index('ix_assessment_invitations_application_status', table_name='assessment_invitations')
    op.drop_table('assessment_invitations')
    # ### end Alembic commands ###
