"""create verification challenges

Revision ID: 42ca27b2f681
Revises: c8dcf70c74b7
Create Date: 2026-09-13 09:03:21.599357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42ca27b2f681'
down_revision: Union[str, Sequence[str], None] = 'c8dcf70c74b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification_challenges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_verification_challenges_active', 'verification_challenges', ['user_id', 'consumed', 'expires_at'], unique=False)
    op.create_index('ix_verification_challenges_expiry', 'verification_challenges', ['expires_at'], unique=False)
    op.create_index('ix_verification_challenges_user_channel_purpose', 'verification_challenges', ['user_id', 'channel', 'purpose'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_verification_challenges_user_channel_purpose', table_name='verification_challenges')
    op.drop_index('ix_verification_challenges_expiry', table_name='verification_challenges')
    op.drop_index('ix_verification_challenges_active', table_name='verification_challenges')
    op.drop_table('verification_challenges')
    # ### end Alembic commands ###
