"""add labour market intelligence foundation

Revision ID: 48e61cb969dc
Revises: 6400dae05d51
Create Date: 2026-09-14 10:41:11.864043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48e61cb969dc'
down_revision: Union[str, Sequence[str], None] = '6400dae05d51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labour_market_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('organization_name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('collection_method', sa.String(length=100), nullable=True),
    sa.Column('reliability_score', sa.Float(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_labour_market_sources_type_active', 'labour_market_sources', ['source_type', 'is_active'], unique=False)
    op.create_index('ix_labour_market_sources_verified', 'labour_market_sources', ['is_verified'], unique=False)
    op.create_table('emerging_skill_trends',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('government_unit_id', sa.UUID(), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('demand_count', sa.Integer(), nullable=False),
    sa.Column('growth_rate', sa.Float(), nullable=False),
    sa.Column('trend_direction', sa.String(length=30), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['government_unit_id'], ['government_units.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_id'], ['labour_market_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_emerging_skill_trends_growth', 'emerging_skill_trends', ['growth_rate'], unique=False)
    op.create_index('ix_emerging_skill_trends_skill', 'emerging_skill_trends', ['skill_id'], unique=False)
    op.create_index('ix_emerging_skill_trends_unit_period', 'emerging_skill_trends', ['government_unit_id', 'period_start', 'period_end'], unique=False)
    op.create_table('labour_market_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('government_unit_id', sa.UUID(), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('skill_id', sa.UUID(), nullable=True),
    sa.Column('occupation_code', sa.String(length=100), nullable=True),
    sa.Column('occupation_name', sa.String(length=200), nullable=False),
    sa.Column('sector', sa.String(length=150), nullable=True),
    sa.Column('employment_type', sa.String(length=50), nullable=True),
    sa.Column('workplace_type', sa.String(length=50), nullable=True),
    sa.Column('experience_min_years', sa.Float(), nullable=True),
    sa.Column('experience_max_years', sa.Float(), nullable=True),
    sa.Column('demand_count', sa.Integer(), nullable=False),
    sa.Column('supply_count', sa.Integer(), nullable=False),
    sa.Column('average_salary', sa.Float(), nullable=True),
    sa.Column('median_salary', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['government_unit_id'], ['government_units.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['labour_market_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_labour_snapshots_occupation', 'labour_market_snapshots', ['occupation_name'], unique=False)
    op.create_index('ix_labour_snapshots_sector', 'labour_market_snapshots', ['sector'], unique=False)
    op.create_index('ix_labour_snapshots_skill', 'labour_market_snapshots', ['skill_id'], unique=False)
    op.create_index('ix_labour_snapshots_unit_period', 'labour_market_snapshots', ['government_unit_id', 'period_start', 'period_end'], unique=False)
    op.create_table('course_alignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('government_unit_id', sa.UUID(), nullable=True),
    sa.Column('demand_score', sa.Float(), nullable=False),
    sa.Column('skill_coverage_score', sa.Float(), nullable=False),
    sa.Column('alignment_score', sa.Float(), nullable=False),
    sa.Column('alignment_status', sa.String(length=40), nullable=False),
    sa.Column('recommended_action', sa.String(length=500), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['government_unit_id'], ['government_units.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'skill_id', 'government_unit_id', name='uq_course_alignment_course_skill_unit')
    )
    op.create_index('ix_course_alignments_course', 'course_alignments', ['course_id'], unique=False)
    op.create_index('ix_course_alignments_skill', 'course_alignments', ['skill_id'], unique=False)
    op.create_index('ix_course_alignments_status', 'course_alignments', ['alignment_status'], unique=False)
    op.create_index('ix_course_alignments_unit', 'course_alignments', ['government_unit_id'], unique=False)
    op.create_table('placement_outcomes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_profile_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=True),
    sa.Column('government_unit_id', sa.UUID(), nullable=True),
    sa.Column('occupation_name', sa.String(length=200), nullable=True),
    sa.Column('sector', sa.String(length=150), nullable=True),
    sa.Column('total_learners', sa.Integer(), nullable=False),
    sa.Column('placed_learners', sa.Integer(), nullable=False),
    sa.Column('employment_rate', sa.Float(), nullable=True),
    sa.Column('average_salary', sa.Float(), nullable=True),
    sa.Column('median_salary', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['government_unit_id'], ['government_units.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['institution_profile_id'], ['institution_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['labour_market_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_placement_outcomes_course', 'placement_outcomes', ['course_id'], unique=False)
    op.create_index('ix_placement_outcomes_institution', 'placement_outcomes', ['institution_profile_id'], unique=False)
    op.create_index('ix_placement_outcomes_occupation', 'placement_outcomes', ['occupation_name'], unique=False)
    op.create_index('ix_placement_outcomes_unit_period', 'placement_outcomes', ['government_unit_id', 'period_start', 'period_end'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_placement_outcomes_unit_period', table_name='placement_outcomes')
    op.drop_index('ix_placement_outcomes_occupation', table_name='placement_outcomes')
    op.drop_index('ix_placement_outcomes_institution', table_name='placement_outcomes')
    op.drop_index('ix_placement_outcomes_course', table_name='placement_outcomes')
    op.drop_table('placement_outcomes')
    op.drop_index('ix_course_alignments_unit', table_name='course_alignments')
    op.drop_index('ix_course_alignments_status', table_name='course_alignments')
    op.drop_index('ix_course_alignments_skill', table_name='course_alignments')
    op.drop_index('ix_course_alignments_course', table_name='course_alignments')
    op.drop_table('course_alignments')
    op.drop_index('ix_labour_snapshots_unit_period', table_name='labour_market_snapshots')
    op.drop_index('ix_labour_snapshots_skill', table_name='labour_market_snapshots')
    op.drop_index('ix_labour_snapshots_sector', table_name='labour_market_snapshots')
    op.drop_index('ix_labour_snapshots_occupation', table_name='labour_market_snapshots')
    op.drop_table('labour_market_snapshots')
    op.drop_index('ix_emerging_skill_trends_unit_period', table_name='emerging_skill_trends')
    op.drop_index('ix_emerging_skill_trends_skill', table_name='emerging_skill_trends')
    op.drop_index('ix_emerging_skill_trends_growth', table_name='emerging_skill_trends')
    op.drop_table('emerging_skill_trends')
    op.drop_index('ix_labour_market_sources_verified', table_name='labour_market_sources')
    op.drop_index('ix_labour_market_sources_type_active', table_name='labour_market_sources')
    op.drop_table('labour_market_sources')
    # ### end Alembic commands ###
