"""create job applications

Revision ID: 5956251f4e06
Revises: 67ae49075bc9
Create Date: 2026-09-14 08:29:11.907892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5956251f4e06'
down_revision: Union[str, Sequence[str], None] = '67ae49075bc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('candidate_profile_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('cover_letter', sa.Text(), nullable=True),
    sa.Column('resume_path', sa.String(length=500), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('matched_required_skills', sa.Integer(), nullable=False),
    sa.Column('required_skills', sa.Integer(), nullable=False),
    sa.Column('employer_notes', sa.Text(), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'candidate_profile_id', name='uq_job_application_job_candidate')
    )
    op.create_index('ix_job_applications_candidate_status', 'job_applications', ['candidate_profile_id', 'status'], unique=False)
    op.create_index('ix_job_applications_job_status', 'job_applications', ['job_id', 'status'], unique=False)
    op.create_index('ix_job_applications_status_applied_at', 'job_applications', ['status', 'applied_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_job_applications_status_applied_at', table_name='job_applications')
    op.drop_index('ix_job_applications_job_status', table_name='job_applications')
    op.drop_index('ix_job_applications_candidate_status', table_name='job_applications')
    op.drop_table('job_applications')
    # ### end Alembic commands ###
