"""create assessment questions

Revision ID: 6400dae05d51
Revises: 679d65359fe0
Create Date: 2026-09-14 08:39:31.324227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6400dae05d51'
down_revision: Union[str, Sequence[str], None] = '679d65359fe0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=40), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('marks', sa.Integer(), nullable=False),
    sa.Column('negative_marks', sa.Float(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id', 'sequence_number', name='uq_assessment_question_sequence')
    )
    op.create_index('ix_assessment_questions_assessment_active', 'assessment_questions', ['assessment_id', 'is_active'], unique=False)
    op.create_index('ix_assessment_questions_skill', 'assessment_questions', ['skill_id'], unique=False)
    op.create_index('ix_assessment_questions_type_difficulty', 'assessment_questions', ['question_type', 'difficulty'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_assessment_questions_type_difficulty', table_name='assessment_questions')
    op.drop_index('ix_assessment_questions_skill', table_name='assessment_questions')
    op.drop_index('ix_assessment_questions_assessment_active', table_name='assessment_questions')
    op.drop_table('assessment_questions')
    # ### end Alembic commands ###
