"""create assessments

Revision ID: 679d65359fe0
Revises: 5956251f4e06
Create Date: 2026-09-14 08:38:02.100477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '679d65359fe0'
down_revision: Union[str, Sequence[str], None] = '5956251f4e06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assessment_type', sa.String(length=40), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('total_marks', sa.Integer(), nullable=False),
    sa.Column('passing_percentage', sa.Float(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('randomize_questions', sa.Boolean(), nullable=False),
    sa.Column('show_result_immediately', sa.Boolean(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'title', name='uq_assessment_organization_title')
    )
    op.create_index('ix_assessments_organization_status', 'assessments', ['organization_id', 'status'], unique=False)
    op.create_index('ix_assessments_published_at', 'assessments', ['published_at'], unique=False)
    op.create_index('ix_assessments_type_status', 'assessments', ['assessment_type', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_assessments_type_status', table_name='assessments')
    op.drop_index('ix_assessments_published_at', table_name='assessments')
    op.drop_index('ix_assessments_organization_status', table_name='assessments')
    op.drop_table('assessments')
    # ### end Alembic commands ###
