"""create candidate credential skill mappings

Revision ID: 67ae49075bc9
Revises: a58719a20cc9
Create Date: 2026-09-14 07:59:57.740115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67ae49075bc9'
down_revision: Union[str, Sequence[str], None] = 'a58719a20cc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_credential_skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('credential_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['credential_id'], ['candidate_credentials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credential_id', 'skill_id', name='uq_candidate_credential_skill')
    )
    op.create_index('ix_candidate_credential_skills_credential', 'candidate_credential_skills', ['credential_id'], unique=False)
    op.create_index('ix_candidate_credential_skills_skill', 'candidate_credential_skills', ['skill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_candidate_credential_skills_skill', table_name='candidate_credential_skills')
    op.drop_index('ix_candidate_credential_skills_credential', table_name='candidate_credential_skills')
    op.drop_table('candidate_credential_skills')
    # ### end Alembic commands ###
