"""create job skill requirements

Revision ID: 69649d21071c
Revises: 1c3102872177
Create Date: 2026-09-13 14:09:23.941714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69649d21071c'
down_revision: Union[str, Sequence[str], None] = '1c3102872177'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_skill_requirements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('skill_name', sa.String(length=255), nullable=False),
    sa.Column('requirement_type', sa.String(length=30), server_default='REQUIRED', nullable=False),
    sa.Column('proficiency_level', sa.String(length=30), server_default='INTERMEDIATE', nullable=False),
    sa.Column('minimum_years', sa.Float(), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'skill_name', name='uq_job_skill_requirement')
    )
    op.create_index('ix_job_skill_requirements_job', 'job_skill_requirements', ['job_id'], unique=False)
    op.create_index('ix_job_skill_requirements_proficiency', 'job_skill_requirements', ['proficiency_level'], unique=False)
    op.create_index('ix_job_skill_requirements_type', 'job_skill_requirements', ['requirement_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_job_skill_requirements_type', table_name='job_skill_requirements')
    op.drop_index('ix_job_skill_requirements_proficiency', table_name='job_skill_requirements')
    op.drop_index('ix_job_skill_requirements_job', table_name='job_skill_requirements')
    op.drop_table('job_skill_requirements')
    # ### end Alembic commands ###
