"""create verifier authorizations

Revision ID: 9dd1d021f0ba
Revises: 007326cfad11
Create Date: 2026-09-13 11:24:59.520386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dd1d021f0ba'
down_revision: Union[str, Sequence[str], None] = '007326cfad11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verifier_authorizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('verifier_user_id', sa.UUID(), nullable=False),
    sa.Column('government_unit_id', sa.UUID(), nullable=True),
    sa.Column('application_type', sa.String(length=50), nullable=False),
    sa.Column('granted_by_user_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['government_unit_id'], ['government_units.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['granted_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['verifier_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_verifier_authorizations_government_unit', 'verifier_authorizations', ['government_unit_id', 'is_active'], unique=False)
    op.create_index('ix_verifier_authorizations_type', 'verifier_authorizations', ['application_type', 'is_active'], unique=False)
    op.create_index('ix_verifier_authorizations_verifier_active', 'verifier_authorizations', ['verifier_user_id', 'is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_verifier_authorizations_verifier_active', table_name='verifier_authorizations')
    op.drop_index('ix_verifier_authorizations_type', table_name='verifier_authorizations')
    op.drop_index('ix_verifier_authorizations_government_unit', table_name='verifier_authorizations')
    op.drop_table('verifier_authorizations')
    # ### end Alembic commands ###
