"""create skills

Revision ID: a0d566c52e05
Revises: 69649d21071c
Create Date: 2026-09-13 19:51:11.307768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0d566c52e05'
down_revision: Union[str, Sequence[str], None] = '69649d21071c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('skill_type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='ACTIVE', nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('normalized_name')
    )
    op.create_index('ix_skills_category_active', 'skills', ['category', 'is_active'], unique=False)
    op.create_index('ix_skills_normalized_name', 'skills', ['normalized_name'], unique=False)
    op.create_index('ix_skills_type_status', 'skills', ['skill_type', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_skills_type_status', table_name='skills')
    op.drop_index('ix_skills_normalized_name', table_name='skills')
    op.drop_index('ix_skills_category_active', table_name='skills')
    op.drop_table('skills')
    # ### end Alembic commands ###
