"""create course skill mappings

Revision ID: a58719a20cc9
Revises: b8bb165e3919
Create Date: 2026-09-14 07:25:32.457947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a58719a20cc9'
down_revision: Union[str, Sequence[str], None] = 'b8bb165e3919'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('importance', sa.String(length=30), server_default='CORE', nullable=False),
    sa.Column('proficiency_level', sa.String(length=30), server_default='BEGINNER', nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('module_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'skill_id', name='uq_course_skill')
    )
    op.create_index('ix_course_skills_course', 'course_skills', ['course_id'], unique=False)
    op.create_index('ix_course_skills_importance', 'course_skills', ['importance'], unique=False)
    op.create_index('ix_course_skills_proficiency', 'course_skills', ['proficiency_level'], unique=False)
    op.create_index('ix_course_skills_skill', 'course_skills', ['skill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_course_skills_skill', table_name='course_skills')
    op.drop_index('ix_course_skills_proficiency', table_name='course_skills')
    op.drop_index('ix_course_skills_importance', table_name='course_skills')
    op.drop_index('ix_course_skills_course', table_name='course_skills')
    op.drop_table('course_skills')
    # ### end Alembic commands ###
