"""create courses

Revision ID: b8bb165e3919
Revises: ba9cd39f577b
Create Date: 2026-09-14 07:24:03.253616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8bb165e3919'
down_revision: Union[str, Sequence[str], None] = 'ba9cd39f577b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_profile_id', sa.UUID(), nullable=False),
    sa.Column('course_code', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('short_description', sa.String(length=1000), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('course_level', sa.String(length=30), server_default='BEGINNER', nullable=False),
    sa.Column('delivery_mode', sa.String(length=30), server_default='OFFLINE', nullable=False),
    sa.Column('duration_value', sa.Integer(), server_default='1', nullable=False),
    sa.Column('duration_unit', sa.String(length=30), server_default='MONTHS', nullable=False),
    sa.Column('fee', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), server_default='INR', nullable=False),
    sa.Column('eligibility', sa.Text(), nullable=True),
    sa.Column('seats', sa.Integer(), nullable=True),
    sa.Column('batch_start_date', sa.Date(), nullable=True),
    sa.Column('batch_end_date', sa.Date(), nullable=True),
    sa.Column('admission_start_date', sa.Date(), nullable=True),
    sa.Column('admission_end_date', sa.Date(), nullable=True),
    sa.Column('syllabus', sa.Text(), nullable=True),
    sa.Column('placement_support', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('placement_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='DRAFT', nullable=False),
    sa.Column('is_featured', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_profile_id'], ['institution_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_code'),
    sa.UniqueConstraint('institution_profile_id', 'title', name='uq_course_institution_title')
    )
    op.create_index('ix_courses_admission_dates', 'courses', ['admission_start_date', 'admission_end_date'], unique=False)
    op.create_index('ix_courses_batch_dates', 'courses', ['batch_start_date', 'batch_end_date'], unique=False)
    op.create_index('ix_courses_delivery_mode', 'courses', ['delivery_mode'], unique=False)
    op.create_index('ix_courses_featured', 'courses', ['is_featured'], unique=False)
    op.create_index('ix_courses_institution', 'courses', ['institution_profile_id'], unique=False)
    op.create_index('ix_courses_level', 'courses', ['course_level'], unique=False)
    op.create_index('ix_courses_status', 'courses', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_courses_status', table_name='courses')
    op.drop_index('ix_courses_level', table_name='courses')
    op.drop_index('ix_courses_institution', table_name='courses')
    op.drop_index('ix_courses_featured', table_name='courses')
    op.drop_index('ix_courses_delivery_mode', table_name='courses')
    op.drop_index('ix_courses_batch_dates', table_name='courses')
    op.drop_index('ix_courses_admission_dates', table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###
