"""create institution profiles

Revision ID: ba9cd39f577b
Revises: 0db7ce7deb61
Create Date: 2026-09-13 23:42:25.024195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba9cd39f577b'
down_revision: Union[str, Sequence[str], None] = '0db7ce7deb61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institution_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('institution_code', sa.String(length=100), nullable=True),
    sa.Column('accreditation_body', sa.String(length=255), nullable=True),
    sa.Column('accreditation_number', sa.String(length=255), nullable=True),
    sa.Column('institution_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), server_default='India', nullable=False),
    sa.Column('verification_status', sa.String(length=50), server_default='PENDING', nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_code'),
    sa.UniqueConstraint('organization_id')
    )
    op.create_index('ix_institution_profiles_active', 'institution_profiles', ['is_active'], unique=False)
    op.create_index('ix_institution_profiles_city_state', 'institution_profiles', ['city', 'state'], unique=False)
    op.create_index('ix_institution_profiles_status', 'institution_profiles', ['verification_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_institution_profiles_status', table_name='institution_profiles')
    op.drop_index('ix_institution_profiles_city_state', table_name='institution_profiles')
    op.drop_index('ix_institution_profiles_active', table_name='institution_profiles')
    op.drop_table('institution_profiles')
    # ### end Alembic commands ###
