"""add verification application jurisdiction

Revision ID: c94ea550fdf5
Revises: 9dd1d021f0ba
Create Date: 2026-09-13 11:45:50.967425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c94ea550fdf5'
down_revision: Union[str, Sequence[str], None] = '9dd1d021f0ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verification_applications', sa.Column('government_unit_id', sa.UUID(), nullable=True))
    op.create_index('ix_verification_applications_government_unit', 'verification_applications', ['government_unit_id', 'status'], unique=False)
    op.create_foreign_key(None, 'verification_applications', 'government_units', ['government_unit_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'verification_applications', type_='foreignkey')
    op.drop_index('ix_verification_applications_government_unit', table_name='verification_applications')
    op.drop_column('verification_applications', 'government_unit_id')
    # ### end Alembic commands ###
