"""add secure private documents

Revision ID: eea37f4248cc
Revises: 7d9363493b3f
Create Date: 2026-09-14 11:59:17.987590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eea37f4248cc'
down_revision: Union[str, Sequence[str], None] = '7d9363493b3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('private_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('scan_status', sa.String(length=30), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_private_documents_hash', 'private_documents', ['sha256_hash'], unique=False)
    op.create_index('ix_private_documents_owner', 'private_documents', ['owner_user_id'], unique=False)
    op.create_index('ix_private_documents_scan_status', 'private_documents', ['scan_status'], unique=False)
    op.create_index('ix_private_documents_type', 'private_documents', ['document_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_private_documents_type', table_name='private_documents')
    op.drop_index('ix_private_documents_scan_status', table_name='private_documents')
    op.drop_index('ix_private_documents_owner', table_name='private_documents')
    op.drop_index('ix_private_documents_hash', table_name='private_documents')
    op.drop_table('private_documents')
    # ### end Alembic commands ###
