"""add_government_unit_fields_and_user_link

Revision ID: efe5119accd6
Revises: ddde381f63cb
Create Date: 2026-09-20 05:56:07.071021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efe5119accd6'
down_revision: Union[str, Sequence[str], None] = 'ddde381f63cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('government_units', sa.Column('status', sa.String(length=40), server_default='ACTIVE', nullable=False))
    op.add_column('government_units', sa.Column('jurisdiction', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('government_unit_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_users_government_unit_id'), 'users', ['government_unit_id'], unique=False)
    op.create_foreign_key('fk_users_government_unit_id_government_units', 'users', 'government_units', ['government_unit_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_government_unit_id_government_units', 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_government_unit_id'), table_name='users')
    op.drop_column('users', 'government_unit_id')
    op.drop_column('government_units', 'jurisdiction')
    op.drop_column('government_units', 'status')
    # ### end Alembic commands ###
