"""create organizations

Revision ID: f65b0b065d81
Revises: c94ea550fdf5
Create Date: 2026-09-13 11:50:57.415115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f65b0b065d81'
down_revision: Union[str, Sequence[str], None] = 'c94ea550fdf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('government_unit_id', sa.UUID(), nullable=True),
    sa.Column('organization_type', sa.String(length=50), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('registration_number', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.String(length=40), server_default='PENDING', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['government_unit_id'], ['government_units.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_organizations_government_unit', 'organizations', ['government_unit_id', 'is_active'], unique=False)
    op.create_index('ix_organizations_owner', 'organizations', ['owner_user_id'], unique=False)
    op.create_index('ix_organizations_registration', 'organizations', ['registration_number'], unique=False)
    op.create_index('ix_organizations_type_status', 'organizations', ['organization_type', 'verification_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_organizations_type_status', table_name='organizations')
    op.drop_index('ix_organizations_registration', table_name='organizations')
    op.drop_index('ix_organizations_owner', table_name='organizations')
    op.drop_index('ix_organizations_government_unit', table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
